# **np.sort**

In [ ]:
# code

import numpy as np
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
b

array([[20, 80, 63, 19],
       [56, 53, 29, 68],
       [11, 43, 51, 95],
       [27, 54, 41, 71],
       [ 5, 40, 88, 11],
       [28, 60, 98, 54]])

In [ ]:
np.sort(a)

array([ 8, 10, 14, 32, 34, 39, 41, 52, 56, 57, 57, 75, 79, 81, 81])

In [ ]:
np.sort(a)[:: -1]

array([81, 81, 79, 75, 57, 57, 56, 52, 41, 39, 34, 32, 14, 10,  8])

In [ ]:
np.sort(b)

array([[19, 20, 63, 80],
       [29, 53, 56, 68],
       [11, 43, 51, 95],
       [27, 41, 54, 71],
       [ 5, 11, 40, 88],
       [28, 54, 60, 98]])

In [ ]:
np.sort(b, axis = 0)

array([[ 5, 40, 29, 11],
       [11, 43, 41, 19],
       [20, 53, 51, 54],
       [27, 54, 63, 68],
       [28, 60, 88, 71],
       [56, 80, 98, 95]])

**np.append**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.append(a , 200)

array([ 75,  10,  39,  56,  57,  41,   8,  34,  32,  57,  79,  52,  81,
        81,  14, 200])

In [ ]:
b

array([[20, 80, 63, 19],
       [56, 53, 29, 68],
       [11, 43, 51, 95],
       [27, 54, 41, 71],
       [ 5, 40, 88, 11],
       [28, 60, 98, 54]])

In [ ]:
np.append(b, np.ones((b.shape[0], 1)),axis = 1)

array([[20., 80., 63., 19.,  1.],
       [56., 53., 29., 68.,  1.],
       [11., 43., 51., 95.,  1.],
       [27., 54., 41., 71.,  1.],
       [ 5., 40., 88., 11.,  1.],
       [28., 60., 98., 54.,  1.]])

In [ ]:
np.append(b, np.ones((1, b.shape[1] )),axis = 0)

array([[20., 80., 63., 19.],
       [56., 53., 29., 68.],
       [11., 43., 51., 95.],
       [27., 54., 41., 71.],
       [ 5., 40., 88., 11.],
       [28., 60., 98., 54.],
       [ 1.,  1.,  1.,  1.]])

## **np.concatenate**

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c , d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**np.unique**

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

**np.expand_dims**

In [ ]:
a.shape

(15,)

In [ ]:
b = np.expand_dims(a, axis = 0)
b

array([[75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14]])

In [ ]:
b.shape

(1, 15)

In [ ]:
np.expand_dims(a, axis = 1)

array([[75],
       [10],
       [39],
       [56],
       [57],
       [41],
       [ 8],
       [34],
       [32],
       [57],
       [79],
       [52],
       [81],
       [81],
       [14]])

**np.where**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.where(a>50)

(array([ 0,  3,  4,  9, 10, 11, 12, 13]),)

In [ ]:
##np.where(condition , true, false)

np.where(a>50 , 0, a)

array([ 0, 10, 39,  0,  0, 41,  8, 34, 32,  0,  0,  0,  0,  0, 14])

**np.argmax**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.argmax(a)

np.int64(12)

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2, 42, 39, 37],
       [68, 56, 17, 23],
       [81, 71, 15, 80],
       [31, 32, 79, 37],
       [52, 13, 87, 62],
       [67, 95,  3, 89]])

In [ ]:
np.argmax(b , axis = 0)

array([2, 5, 4, 5])

In [ ]:
np.argmin(a)

np.int64(6)

**np.cumsum**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.cumsum(a)

array([ 75,  85, 124, 180, 237, 278, 286, 320, 352, 409, 488, 540, 621,
       702, 716])

In [ ]:
b

array([[ 2, 42, 39, 37],
       [68, 56, 17, 23],
       [81, 71, 15, 80],
       [31, 32, 79, 37],
       [52, 13, 87, 62],
       [67, 95,  3, 89]])

In [ ]:
np.cumsum(b)

array([   2,   44,   83,  120,  188,  244,  261,  284,  365,  436,  451,
        531,  562,  594,  673,  710,  762,  775,  862,  924,  991, 1086,
       1089, 1178])

In [ ]:
np.cumsum(b , axis = 0)

array([[  2,  42,  39,  37],
       [ 70,  98,  56,  60],
       [151, 169,  71, 140],
       [182, 201, 150, 177],
       [234, 214, 237, 239],
       [301, 309, 240, 328]])

In [ ]:
# np.cumprod

a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.cumprod(a)

array([                  75,                  750,                29250,
                    1638000,             93366000,           3828006000,
                30624048000,        1041217632000,       33318964224000,
           1899180960768000,   150035295900672000,  7801835386834944000,
        4759367827505709056, -1872831519938150400, -7772897205424553984])

**np.percentile**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.percentile(a , 100)

np.float64(81.0)

In [ ]:
np.percentile(a , 50)

np.float64(52.0)

In [ ]:
np.median(a)

np.float64(52.0)

**np.histogram**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.histogram(a, bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 0, 3, 1, 4, 0, 2, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

**np.corrcoef**

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

**np.isin**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a , items)]

array([10])

**np.flip**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.flip(a)

array([14, 81, 81, 52, 79, 57, 32, 34,  8, 41, 57, 56, 39, 10, 75])

In [ ]:
b

array([[ 2, 42, 39, 37],
       [68, 56, 17, 23],
       [81, 71, 15, 80],
       [31, 32, 79, 37],
       [52, 13, 87, 62],
       [67, 95,  3, 89]])

In [ ]:
np.flip(b)

array([[89,  3, 95, 67],
       [62, 87, 13, 52],
       [37, 79, 32, 31],
       [80, 15, 71, 81],
       [23, 17, 56, 68],
       [37, 39, 42,  2]])

In [ ]:
np.flip(b, axis = 0)

array([[67, 95,  3, 89],
       [52, 13, 87, 62],
       [31, 32, 79, 37],
       [81, 71, 15, 80],
       [68, 56, 17, 23],
       [ 2, 42, 39, 37]])

**np.put**

In [ ]:
a

array([75, 10, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.put(a, [0,1], [20,30])

In [ ]:
a

array([20, 30, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

np.delete

In [ ]:
a

array([20, 30, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.delete(a, [0,2,4])

array([30, 56, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
a

array([20, 30, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

# **Set functions**

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
np.union1d(n,m)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.isin(m , 1)]

array([1])

**np.clip**

In [ ]:
a

array([20, 30, 39, 56, 57, 41,  8, 34, 32, 57, 79, 52, 81, 81, 14])

In [ ]:
np.clip(a, a_min = 25, a_max = 75)

array([25, 30, 39, 56, 57, 41, 25, 34, 32, 57, 75, 52, 75, 75, 25])