# **Numpy**

**Creating numpy array**

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#2D array

c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D

d = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype

a = np.array([1,2,3], dtype = 'float')
print(a)

[1. 2. 3.]


In [ ]:
# np.arange

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
 # np.ones

 np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random

np.random.random((3,4))

array([[0.90282003, 0.55353732, 0.75902938, 0.57312148],
       [0.3519561 , 0.06883242, 0.66069888, 0.03972335],
       [0.97967304, 0.52294324, 0.49832925, 0.14177316]])

In [ ]:
# np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [ ]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12 , dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
a3.shape

(2, 2, 2)

In [ ]:
# size

a3.size

8

In [ ]:
# itemsize

a3.itemsize

8

In [ ]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing data tyes**

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array operation**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
#scalar operation

# arithmatic
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# relaional

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations

# arithmatic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

**Array functions**

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[68., 17., 17.],
       [77., 15., 85.],
       [90., 22.,  8.]])

In [ ]:
#max/mim/sum/product
np.max(a1)


np.float64(90.0)

In [ ]:
np.min(a1)

np.float64(8.0)

In [ ]:
np.sum(a1)

np.float64(399.0)

In [ ]:
np.prod(a1)

np.float64(30560667984000.0)

In [ ]:
np.max(a1 , axis = 1)

array([68., 85., 90.])

In [ ]:
np.max(a1 , axis = 0)

array([90., 22., 85.])

In [ ]:
#mean median std var

In [ ]:
np.mean(a1)

np.float64(44.333333333333336)

In [ ]:
np.mean(a1 , axis = 1)

array([34., 59., 40.])

In [ ]:
np.median(a1 , axis = 1)

array([17., 77., 22.])

In [ ]:
np.std(a1 , axis = 1)

array([24.04163056, 31.28364855, 35.81433605])

In [ ]:
# trignometric

In [ ]:
np.sin(a1)

array([[-0.89792768, -0.96139749, -0.96139749],
       [ 0.99952016,  0.65028784, -0.17607562],
       [ 0.89399666, -0.00885131,  0.98935825]])

In [ ]:
#dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a1 , a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponent

np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
np.log(a1)

/tmp/ipython-input-2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
# round floor ceil

y = np.random.random((2,3))*100
np.round(y)

array([[ 7., 97., 72.],
       [ 4., 40., 86.]])

In [ ]:
np.floor(y)

array([[ 6., 97., 71.],
       [ 4., 39., 86.]])

In [ ]:
np.ceil(y)

array([[ 7., 98., 72.],
       [ 5., 40., 87.]])

**Indexing and slice**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1[0]

np.int64(0)

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a2[1, 2]

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1, 0, 1]

np.int64(5)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0]

array([0, 1, 2, 3])

In [ ]:
a2[0, :]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2, 1::2,]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1, ::3]

array([4, 7])

In [ ]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0, 1, :]

array([3, 4, 5])

In [ ]:
a3[1, :, 1]

array([10, 13, 16])

In [ ]:
a3[2,1:, 1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2 :
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3 :
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3) :
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# tanspose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [ ]:
 # Horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)



In [ ]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vettical stack

np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [ ]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]